import { Injectable, Logger } from '@nestjs/common';
import { InjectRepository } from '@nestjs/typeorm';
import { Repository } from 'typeorm';
import { Notification } from '../../database/entities/audit-log.entity';
import { EventsGateway } from '../../websocket/events.gateway';
let nodemailer: any;
try {
  nodemailer = require('nodemailer');
} catch {
  nodemailer = null;
}

export interface CreateNotificationDto {
  userId: string;
  type: string;
  title: string;
  message: string;
  metadata?: Record<string, any>;
  relatedEntityType?: string;
  relatedEntityId?: string;
}

interface DispatchConfig {
  email?: { enabled: boolean; to: string[] };
  slack?: { enabled: boolean; webhookUrl: string };
  webhook?: { enabled: boolean; url: string; headers?: Record<string, string> };
}

@Injectable()
export class NotificationService {
  private readonly logger = new Logger(NotificationService.name);
  private emailTransporter: any = null;

  constructor(
    @InjectRepository(Notification) private notifRepo: Repository<Notification>,
    private wsGateway: EventsGateway,
  ) {
    this.initEmailTransporter();
  }

  private initEmailTransporter() {
    const smtpHost = process.env.SMTP_HOST;
    const smtpPort = parseInt(process.env.SMTP_PORT || '587');
    const smtpUser = process.env.SMTP_USER;
    const smtpPass = process.env.SMTP_PASS;

    if (smtpHost && smtpUser && smtpPass) {
      this.emailTransporter = nodemailer.createTransport({
        host: smtpHost,
        port: smtpPort,
        secure: smtpPort === 465,
        auth: { user: smtpUser, pass: smtpPass },
      });
      this.logger.log('Email transporter initialized');
    }
  }

  async create(dto: CreateNotificationDto): Promise<Notification> {
    const notif = this.notifRepo.create(dto);
    const saved = await this.notifRepo.save(notif);
    this.wsGateway.broadcastNotification(dto.userId, saved);
    return saved;
  }

  async createBulk(dtos: CreateNotificationDto[]): Promise<Notification[]> {
    const notifs = dtos.map(d => this.notifRepo.create(d));
    const saved = await this.notifRepo.save(notifs);
    for (const n of saved) {
      this.wsGateway.broadcastNotification(n.userId, n);
    }
    return saved;
  }

  async findByUser(userId: string, unreadOnly = false): Promise<Notification[]> {
    const where: any = { userId };
    if (unreadOnly) where.status = 'unread';
    return this.notifRepo.find({ where, order: { createdAt: 'DESC' }, take: 50 });
  }

  async markAsRead(id: string): Promise<void> {
    await this.notifRepo.update(id, { status: 'read' });
  }

  async markAllAsRead(userId: string): Promise<void> {
    await this.notifRepo.update({ userId, status: 'unread' }, { status: 'read' });
  }

  async getUnreadCount(userId: string): Promise<number> {
    return this.notifRepo.count({ where: { userId, status: 'unread' } });
  }

  async notifyAlertCreated(alert: any) {
    const admins = await this.notifRepo.query(
      `SELECT id FROM users WHERE role = 'admin' AND "isActive" = true`
    );
    for (const admin of admins) {
      await this.create({
        userId: admin.id,
        type: 'alert',
        title: `New ${alert.severity} alert: ${alert.title}`,
        message: alert.description || 'Alert generated by correlation engine',
        relatedEntityType: 'alert',
        relatedEntityId: alert.id,
      });
    }
  }

  async notifyIncidentCreated(incident: any) {
    const admins = await this.notifRepo.query(
      `SELECT id FROM users WHERE role = 'admin' AND "isActive" = true`
    );
    for (const admin of admins) {
      await this.create({
        userId: admin.id,
        type: 'incident',
        title: `New ${incident.severity} incident: ${incident.title}`,
        message: incident.description || 'Incident created',
        relatedEntityType: 'incident',
        relatedEntityId: incident.id,
      });
    }
  }

  async dispatch(notification: Notification, config: DispatchConfig) {
    const promises: Promise<void>[] = [];

    if (config.email?.enabled && this.emailTransporter) {
      promises.push(this.sendEmail(config.email.to, notification));
    }

    if (config.slack?.enabled && config.slack.webhookUrl) {
      promises.push(this.sendSlack(config.slack.webhookUrl, notification));
    }

    if (config.webhook?.enabled && config.webhook.url) {
      promises.push(this.sendWebhook(config.webhook.url, config.webhook.headers, notification));
    }

    await Promise.allSettled(promises);
  }

  private async sendEmail(to: string[], notification: Notification) {
    if (!this.emailTransporter) return;
    try {
      await this.emailTransporter.sendMail({
        from: process.env.SMTP_FROM || 'blacksentinel@security.local',
        to: to.join(','),
        subject: `[BlackSentinel] ${notification.title}`,
        html: `
          <div style="font-family: Arial, sans-serif; max-width: 600px;">
            <div style="background: #FF6B00; color: white; padding: 16px; text-align: center;">
              <h2 style="margin: 0;">BlackSentinel Nexus</h2>
            </div>
            <div style="padding: 20px; background: #f9f9f9;">
              <h3 style="color: #333;">${notification.title}</h3>
              <p style="color: #666;">${notification.message}</p>
              <p style="color: #999; font-size: 12px;">Type: ${notification.type} | ${new Date(notification.createdAt).toLocaleString()}</p>
            </div>
          </div>
        `,
      });
      this.logger.log(`Email sent for notification: ${notification.id}`);
    } catch (error: any) {
      this.logger.error(`Email dispatch failed: ${error.message}`);
    }
  }

  private async sendSlack(webhookUrl: string, notification: Notification) {
    try {
      const color = notification.type === 'alert' ? '#FF6B00' : notification.type === 'incident' ? '#ff4444' : '#333333';
      await fetch(webhookUrl, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          attachments: [{
            color,
            title: notification.title,
            text: notification.message,
            footer: 'BlackSentinel Nexus',
            ts: Math.floor(new Date(notification.createdAt).getTime() / 1000),
          }],
        }),
      });
      this.logger.log(`Slack notification sent: ${notification.id}`);
    } catch (error: any) {
      this.logger.error(`Slack dispatch failed: ${error.message}`);
    }
  }

  private async sendWebhook(url: string, headers: Record<string, string> | undefined, notification: Notification) {
    try {
      await fetch(url, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          ...headers,
        },
        body: JSON.stringify({
          event: 'notification',
          data: {
            id: notification.id,
            type: notification.type,
            title: notification.title,
            message: notification.message,
            createdAt: notification.createdAt,
          },
        }),
      });
      this.logger.log(`Webhook sent: ${notification.id}`);
    } catch (error: any) {
      this.logger.error(`Webhook dispatch failed: ${error.message}`);
    }
  }
}
